language: java
sudo: false
# install: ./mvnw clean install #mvn install

# script: ./mvnw clean install

notifications:
  email: alper.cinaroglu@gmail.com


dist: focal

jdk:
  - openjdk11

git:
  depth: false

# Sonar cloud addons on travis has some issues so that it's used directly 
#addons:
#  sonarcloud:
#    organization: "ant-media"
#    token: $SONAR_TOKEN

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V --quiet

#before_script:
#  - sudo chmod -R 777 /tmp


script:
  - export RELEASE_VERSION="$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)"
  - echo $RELEASE_VERSION
  # option to add above (-Dtest="MuxerUnitTest")  for running custom tests
  - mvn org.owasp:dependency-check-maven:check --quiet
#depedency vulnerability check

